'use client'
import { useState } from 'react'
import Link from 'next/link'
import { Search, ArrowLeft, ExternalLink } from 'lucide-react'

export default function DealsPage() {
  const [query, setQuery] = useState('Samsung A55')
  const [items, setItems] = useState<any[]>([])
  const [status, setStatus] = useState('')
  async function search() { setStatus('Searching eBay…'); const response = await fetch(`/api/earning/deals?q=${encodeURIComponent(query)}`); const data = await response.json(); setItems(data.items || []); setStatus(data.success ? `${data.total} offers found` : data.message) }
  return <main className="min-h-screen bg-bg px-4 py-8 sm:px-6"><div className="mx-auto max-w-6xl"><Link href="/dashboard/earn" className="inline-flex items-center gap-2 text-sm font-semibold text-indigo-600"><ArrowLeft className="w-4 h-4" /> Earning hub</Link><div className="mt-6 rounded-2xl border border-border bg-surface p-6"><p className="text-sm font-semibold text-indigo-600">Deal Finder</p><h1 className="mt-1 text-3xl font-bold text-heading">Compare prices before you buy</h1><p className="mt-2 text-text-muted">Powered by the eBay Browse API. Prices, shipping and seller feedback are fetched server-side.</p><form onSubmit={(event) => { event.preventDefault(); search() }} className="mt-6 flex gap-3"><label htmlFor="product-search" className="sr-only">Search products</label><input id="product-search" value={query} onChange={(event) => setQuery(event.target.value)} className="min-w-0 flex-1 rounded-xl border border-border bg-bg px-4 py-3 text-heading" /><button className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 font-semibold text-white"><Search className="w-4 h-4" /> Search</button></form><p className="mt-3 text-sm text-text-muted" aria-live="polite">{status}</p></div><div className="mt-6 grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">{items.map((item) => <article key={item.id} className="rounded-2xl border border-border bg-surface p-5"><div className="flex min-h-24 items-center justify-center rounded-xl bg-bg-subtle">{item.image ? <img src={item.image} alt="" className="max-h-24 max-w-full object-contain" /> : <Search className="w-8 h-8 text-text-muted" />}</div><h2 className="mt-4 line-clamp-2 font-semibold text-heading">{item.title}</h2><p className="mt-3 text-2xl font-bold text-heading">{item.currency} {item.price}</p><p className="mt-1 text-sm text-text-muted">Shipping: {item.shipping ?? 'See offer'} · Seller: {item.sellerRating ?? '—'}%</p><a href={item.url} className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-indigo-600">Shop now <ExternalLink className="w-4 h-4" /></a></article>)}</div></div></main>
}
